#!/bin/bash
clang++ -x c++ -Wall -std=c++23 main.cpp -o sat

for file in generators/*.cpp; do
    [ -e "$file" ] || continue
    clang++ -x c++ -Wall -std=c++23 -L ./dependencies/kissat/build/ -l kissat $file -o ${file/.cpp/}
done