#!/bin/bash
echo "Rebuild"
./build

echo "Run Tests"
for testfile in tests/*.cnf; do
    [ -e "$testfile" ] || continue
    echo "---- $testfile ----"
    time ./sat $testfile > ${testfile/cnf/out} 2> /dev/null
    if grep -Fxq "UNSAT" ${testfile/cnf/out}
    then
        echo "Solver claims UNSAT"
    else
        echo "verify solution with kissat"
        cat $testfile ${testfile/cnf/out} | ./kissat --relaxed > /dev/null
        if [ $? -ne 10 ]; then
            echo "KISSAT verification failed"
            exit 1
        fi
    fi
done